export default {
  site: 'http://localhost:8888',
  urls: [
    "/404.dc.html",
    "/Accesibilidad.dc.html",
    "/Accion-print-mn7reu.dc.html",
    "/Accion.dc.html",
    "/home-print.dc.html",
    "/",
    "/Actualidad.dc.html",
    "/Agenda.dc.html",
    "/AvisoLegal.dc.html",
    "/Barrio-beniopa.dc.html",
    "/Barrio-benipeixcar.dc.html",
    "/Barrio-corea.dc.html",
    "/Barrio-grao.dc.html",
    "/Barrio.dc.html",
    "/Buscador.dc.html",
    "/Campanas.dc.html",
    "/Categoria.dc.html",
    "/CategoriaCultura.dc.html",
    "/CategoriaEmpleo.dc.html",
    "/CategoriaGandiaUnida.dc.html",
    "/CategoriaSeguridad.dc.html",
    "/CategoriaServicios.dc.html",
    "/Ciudadano.dc.html",
    "/ComoFunciona.dc.html",
    "/Conocenos.dc.html",
    "/Contacto.dc.html",
    "/Cookies.dc.html",
    "/Crear.dc.html",
    "/CrearPropuesta.dc.html",
    "/DetalleActuacion-bici.dc.html",
    "/DetalleActuacion-camaras.dc.html",
    "/DetalleActuacion-grao.dc.html",
    "/DetalleActuacion.dc.html",
    "/DetalleCampana-antiokupacion.dc.html",
    "/DetalleCampana-mesas.dc.html",
    "/DetalleCampana.dc.html",
    "/DetallePublicacion-camaras.dc.html",
    "/DetallePublicacion-mesas.dc.html",
    "/DetallePublicacion.dc.html",
    "/Equipo.dc.html",
    "/FAQ.dc.html",
    "/FichaEvento-asamblea.dc.html",
    "/FichaEvento-barrio.dc.html",
    "/FichaEvento.dc.html",
    "/Historia.dc.html",
    "/MapaActuaciones.dc.html",
    "/Participa.dc.html",
    "/Participacion.dc.html",
    "/PerfilMiembro-mesa.dc.html",
    "/PerfilMiembro-mondejar.dc.html",
    "/PerfilMiembro-reig.dc.html",
    "/PerfilMiembro-sanchez.dc.html",
    "/PerfilMiembro-sendroiu.dc.html",
    "/PerfilMiembro-tormo.dc.html",
    "/PerfilMiembro-vila.dc.html",
    "/PerfilMiembro.dc.html",
    "/Privacidad.dc.html",
    "/ProgramaPDF.dc.html",
    "/ProgramaElectoral.dc.html",
    "/Comunidad.dc.html",
    "/PropuestaCiudadana.dc.html",
    "/PropuestaComercio.dc.html",
    "/PropuestaDesestacionalizacion.dc.html",
    "/PropuestaDetalle.dc.html",
    "/Propuestas.dc.html",
    "/Sitemap.dc.html",
    "/Transparencia.dc.html",
    "/Valores.dc.html"
],
  scanner: {
    device: 'desktop',
    dynamicSampling: false,
    skipJavascript: false
  }
}
