const iso = (value) => new Date(value).toISOString();

// Lista canónica única de barrios/distritos de Gandia (misma en admin, Crear propuesta y Voluntarios).
export const seedBarrios = [
  { slug: 'centro', nombre_es: 'Centro Histórico', nombre_va: 'Centre Històric', orden: 10, lat: 38.9683, lng: -0.1847 },
  { slug: 'raval', nombre_es: 'El Raval – El Prado', nombre_va: 'El Raval – El Prado', orden: 20, lat: null, lng: null },
  { slug: 'germanies', nombre_es: 'Germanies – Els Jardinets', nombre_va: 'Germanies – Els Jardinets', orden: 30, lat: null, lng: null },
  { slug: 'republica-argentina', nombre_es: 'Pl. El·líptica – Rep. Argentina', nombre_va: 'Pl. El·líptica – Rep. Argentina', orden: 40, lat: null, lng: null },
  { slug: 'corea', nombre_es: 'Corea', nombre_va: 'Corea', orden: 50, lat: 38.9648, lng: -0.1713 },
  { slug: 'santa-anna', nombre_es: 'Santa Anna', nombre_va: 'Santa Anna', orden: 60, lat: null, lng: null },
  { slug: 'beniopa', nombre_es: 'Beniopa – Sant Pere', nombre_va: 'Beniopa – Sant Pere', orden: 70, lat: 38.9802, lng: -0.1974 },
  { slug: 'benipeixcar', nombre_es: 'Benipeixcar', nombre_va: 'Benipeixcar', orden: 80, lat: 38.9716, lng: -0.1762 },
  { slug: 'grao', nombre_es: 'Grau – Venècia – Rafalcaid', nombre_va: 'Grau – Venècia – Rafalcaid', orden: 90, lat: 38.9952, lng: -0.1535 },
  { slug: 'playa', nombre_es: 'Playa de Gandia', nombre_va: 'Platja de Gandia', orden: 100, lat: null, lng: null },
  { slug: 'marchuquera', nombre_es: 'Marxuquera', nombre_va: 'Marxuquera', orden: 110, lat: null, lng: null },
];

export const seedPosts = [
  {
    slug: 'nit-dels-ciris',
    tipo: 'noticia',
    titulo_es: 'Acción Civil participa en la Nit dels Ciris de Benipeixcar',
    titulo_va: 'Acció Civil participa en la Nit dels Ciris de Benipeixcar',
    extracto_es: 'Los miembros de Acción Civil Gandia compartieron con el barrio una noche simbólica que refuerza la vida vecinal.',
    extracto_va: 'Els membres d’Acció Civil Gandia van compartir amb el barri una nit simbòlica que reforça la vida veïnal.',
    cuerpo_es: 'Crónica de la participación del equipo en la Nit dels Ciris de Benipeixcar.',
    cuerpo_va: 'Crònica de la participació de l’equip en la Nit dels Ciris de Benipeixcar.',
    imagen: 'assets/web/og-accion-en-gandia.webp',
    video_url: null,
    estado: 'publicado',
    publicado_at: iso('2026-06-20T10:00:00+02:00'),
    created_at: iso('2026-06-20T10:00:00+02:00'),
  },
  {
    slug: 'camaras',
    tipo: 'comunicado',
    titulo_es: 'Posición sobre las 38 cámaras de seguridad',
    titulo_va: 'Posició sobre les 38 càmeres de seguretat',
    extracto_es: 'La propuesta debe ejecutarse con criterio, utilidad real y equilibrio entre seguridad y convivencia.',
    extracto_va: 'La proposta s’ha d’executar amb criteri, utilitat real i equilibri entre seguretat i convivència.',
    cuerpo_es: 'Comunicado sobre la implantación de cámaras de seguridad en Gandia.',
    cuerpo_va: 'Comunicat sobre la implantació de càmeres de seguretat a Gandia.',
    imagen: 'assets/web/og-propuestas-seguridad.webp',
    video_url: null,
    estado: 'publicado',
    publicado_at: iso('2026-06-28T10:00:00+02:00'),
    created_at: iso('2026-06-28T10:00:00+02:00'),
  },
  {
    slug: 'mesas',
    tipo: 'noticia',
    titulo_es: 'Mesa informativa en el barrio del Jardinet',
    titulo_va: 'Taula informativa al barri del Jardinet',
    extracto_es: 'El equipo salió a la calle para compartir propuestas y escuchar prioridades del vecindario.',
    extracto_va: 'L’equip va eixir al carrer per compartir propostes i escoltar prioritats del veïnat.',
    cuerpo_es: 'Resumen de la jornada informativa en el barrio del Jardinet.',
    cuerpo_va: 'Resum de la jornada informativa al barri del Jardinet.',
    imagen: 'assets/web/og-accion-en-gandia-barrio.webp',
    video_url: null,
    estado: 'publicado',
    publicado_at: iso('2026-06-15T10:00:00+02:00'),
    created_at: iso('2026-06-15T10:00:00+02:00'),
  },
  {
    slug: 'oficina-antiokupacion',
    tipo: 'noticia',
    titulo_es: 'Acción Civil apoya la creación de una oficina antiokupación',
    titulo_va: 'Acció Civil dona suport a la creació d’una oficina antiokupació',
    extracto_es: 'La propuesta plantea atención especializada para vecinos afectados y seguimiento municipal serio.',
    extracto_va: 'La proposta planteja atenció especialitzada per a veïns afectats i seguiment municipal seriós.',
    cuerpo_es: 'Nota sobre la oficina antiokupación propuesta por Acción Civil Gandia.',
    cuerpo_va: 'Nota sobre l’oficina antiokupació proposada per Acció Civil Gandia.',
    imagen: 'assets/web/og-campanas-detalle.webp',
    video_url: null,
    estado: 'publicado',
    publicado_at: iso('2026-06-10T10:00:00+02:00'),
    created_at: iso('2026-06-10T10:00:00+02:00'),
  },
  {
    slug: 'balance-legislatura',
    tipo: 'comunicado',
    titulo_es: 'Balance de tres años de legislatura',
    titulo_va: 'Balanç de tres anys de legislatura',
    extracto_es: 'La formación resume prioridades, aprendizajes y trabajo acumulado antes del ciclo electoral de 2027.',
    extracto_va: 'La formació resumeix prioritats, aprenentatges i treball acumulat abans del cicle electoral de 2027.',
    cuerpo_es: 'Balance político y organizativo de los últimos tres años.',
    cuerpo_va: 'Balanç polític i organitzatiu dels últims tres anys.',
    imagen: 'assets/web/og-propuestas-programa.webp',
    video_url: null,
    estado: 'publicado',
    publicado_at: iso('2026-05-10T10:00:00+02:00'),
    created_at: iso('2026-05-10T10:00:00+02:00'),
  },
  {
    slug: 'entrevista-fundacional',
    tipo: 'entrevista',
    titulo_es: 'Entrevista fundacional en Gente de la Safor',
    titulo_va: 'Entrevista fundacional a Gente de la Safor',
    extracto_es: 'Los fundadores explican la visión municipalista y vecinal del proyecto.',
    extracto_va: 'Els fundadors expliquen la visió municipalista i veïnal del projecte.',
    cuerpo_es: 'Entrevista de presentación del proyecto político.',
    cuerpo_va: 'Entrevista de presentació del projecte polític.',
    imagen: 'assets/web/og-conocenos.webp',
    video_url: null,
    estado: 'publicado',
    publicado_at: iso('2023-01-03T10:00:00+01:00'),
    created_at: iso('2023-01-03T10:00:00+01:00'),
  },
];

export const seedEvents = [
  {
    slug: 'asamblea',
    titulo_es: 'Asamblea general trimestral',
    titulo_va: 'Assemblea general trimestral',
    descripcion_es: 'Balance del trimestre, cuentas y prioridades para el siguiente periodo.',
    descripcion_va: 'Balanç del trimestre, comptes i prioritats per al període següent.',
    fecha: '2026-07-24',
    hora_inicio: '19:00:00',
    hora_fin: '21:30:00',
    lugar: 'Centro Cultural, Grau',
    direccion: 'Grau de Gandia',
    barrio_slug: 'grao',
    barrio_nombre_es: 'Playa-Grao',
    barrio_nombre_va: 'Platja-Grau',
    estado: 'publicado',
    created_at: iso('2026-06-24T10:00:00+02:00'),
  },
  {
    slug: 'mesa-barrio',
    titulo_es: 'Mesa informativa en el barrio',
    titulo_va: 'Taula informativa al barri',
    descripcion_es: 'Encuentro de calle para escuchar propuestas y explicar campañas activas.',
    descripcion_va: 'Trobada al carrer per escoltar propostes i explicar campanyes actives.',
    fecha: '2026-07-10',
    hora_inicio: '18:00:00',
    hora_fin: '20:00:00',
    lugar: 'Sede Acción Civil',
    direccion: 'Gandia',
    barrio_slug: 'centro',
    barrio_nombre_es: 'Centro',
    barrio_nombre_va: 'Centre',
    estado: 'publicado',
    created_at: iso('2026-06-20T10:00:00+02:00'),
  },
  {
    slug: 'pleno-julio',
    titulo_es: 'Pleno municipal ordinario de julio',
    titulo_va: 'Ple municipal ordinari de juliol',
    descripcion_es: 'Seguimiento institucional y defensa de propuestas sobre vivienda y litoral.',
    descripcion_va: 'Seguiment institucional i defensa de propostes sobre habitatge i litoral.',
    fecha: '2026-07-17',
    hora_inicio: '10:00:00',
    hora_fin: '13:00:00',
    lugar: 'Ayuntamiento de Gandia',
    direccion: 'Gandia',
    barrio_slug: 'centro',
    barrio_nombre_es: 'Centro',
    barrio_nombre_va: 'Centre',
    estado: 'publicado',
    created_at: iso('2026-06-21T10:00:00+02:00'),
  },
  {
    slug: 'taller-propuestas',
    titulo_es: 'Taller: cómo hacer una propuesta ciudadana',
    titulo_va: 'Taller: com fer una proposta ciutadana',
    descripcion_es: 'Sesión práctica para aprender a redactar propuestas útiles y accionables.',
    descripcion_va: 'Sessió pràctica per aprendre a redactar propostes útils i accionables.',
    fecha: '2026-07-19',
    hora_inicio: '11:00:00',
    hora_fin: '13:00:00',
    lugar: 'Biblioteca Central',
    direccion: 'Gandia',
    barrio_slug: 'centro',
    barrio_nombre_es: 'Centro',
    barrio_nombre_va: 'Centre',
    estado: 'publicado',
    created_at: iso('2026-06-22T10:00:00+02:00'),
  },
  {
    slug: 'asamblea-barrial-centro',
    titulo_es: 'Asamblea barrial — Centro histórico',
    titulo_va: 'Assemblea de barri — Centre històric',
    descripcion_es: 'Revisión de prioridades y nuevas incidencias del barrio.',
    descripcion_va: 'Revisió de prioritats i noves incidències del barri.',
    fecha: '2026-07-05',
    hora_inicio: '19:00:00',
    hora_fin: '20:30:00',
    lugar: 'Casal Jove, Centre',
    direccion: 'Gandia',
    barrio_slug: 'centro',
    barrio_nombre_es: 'Centro',
    barrio_nombre_va: 'Centre',
    estado: 'publicado',
    created_at: iso('2026-06-18T10:00:00+02:00'),
  },
  {
    slug: 'asamblea-semestral',
    titulo_es: 'Asamblea abierta: balance primer semestre',
    titulo_va: 'Assemblea oberta: balanç primer semestre',
    descripcion_es: 'Encuentro abierto ya celebrado para compartir balance del semestre.',
    descripcion_va: 'Trobada oberta ja celebrada per compartir balanç del semestre.',
    fecha: '2026-06-25',
    hora_inicio: '19:00:00',
    hora_fin: '21:00:00',
    lugar: 'Gandia',
    direccion: 'Gandia',
    barrio_slug: 'centro',
    barrio_nombre_es: 'Centro',
    barrio_nombre_va: 'Centre',
    estado: 'publicado',
    created_at: iso('2026-06-10T10:00:00+02:00'),
  },
];

export const seedCampaigns = [
  {
    slug: '38-camaras-seguridad',
    titulo_es: '38 cámaras de seguridad para Gandia',
    titulo_va: '38 càmeres de seguretat per a Gandia',
    descripcion_es: 'Seguimiento público a la propuesta de cámaras con foco en utilidad real y cobertura equilibrada.',
    descripcion_va: 'Seguiment públic a la proposta de càmeres amb focus en utilitat real i cobertura equilibrada.',
    imagen: 'assets/web/og-propuestas-seguridad.webp',
    destacada: true,
    progreso: 38,
    objetivos: [],
    cronologia: [],
    docs: [],
    estado: 'activa',
    created_at: iso('2026-06-28T10:00:00+02:00'),
  },
  {
    slug: 'antiokupacion',
    titulo_es: 'Oficina antiokupación para Gandia',
    titulo_va: 'Oficina antiokupació per a Gandia',
    descripcion_es: 'Campaña para activar una respuesta municipal especializada frente a la ocupación conflictiva.',
    descripcion_va: 'Campanya per activar una resposta municipal especialitzada davant l’ocupació conflictiva.',
    imagen: 'assets/web/og-campanas-detalle.webp',
    destacada: false,
    progreso: 62,
    objetivos: [],
    cronologia: [],
    docs: [],
    estado: 'activa',
    created_at: iso('2026-06-12T10:00:00+02:00'),
  },
  {
    slug: 'mesas',
    titulo_es: 'Mesas informativas por los barrios',
    titulo_va: 'Taules informatives pels barris',
    descripcion_es: 'Presencia permanente en la calle para escuchar vecinos y dar seguimiento a propuestas.',
    descripcion_va: 'Presència permanent al carrer per escoltar veïns i donar seguiment a propostes.',
    imagen: 'assets/web/og-accion-en-gandia-barrio.webp',
    destacada: false,
    progreso: 71,
    objetivos: [],
    cronologia: [],
    docs: [],
    estado: 'activa',
    created_at: iso('2026-06-08T10:00:00+02:00'),
  },
  {
    slug: 'candidatura-28m-2023',
    titulo_es: 'Candidatura elecciones 28M 2023',
    titulo_va: 'Candidatura eleccions 28M 2023',
    descripcion_es: 'Campaña ya cerrada vinculada a la presentación de la candidatura municipal.',
    descripcion_va: 'Campanya ja tancada vinculada a la presentació de la candidatura municipal.',
    imagen: 'assets/web/og-conocenos.webp',
    destacada: false,
    progreso: 100,
    objetivos: [],
    cronologia: [],
    docs: [],
    estado: 'finalizada',
    created_at: iso('2023-05-10T10:00:00+02:00'),
  },
];

export const seedActuaciones = [
  {
    slug: 'nit-dels-ciris',
    titulo_es: 'Nit dels Ciris en Benipeixcar',
    titulo_va: 'Nit dels Ciris a Benipeixcar',
    descripcion_es: 'Participación del equipo en un acto vecinal simbólico para reforzar la presencia comunitaria.',
    descripcion_va: 'Participació de l’equip en un acte veïnal simbòlic per reforçar la presència comunitària.',
    barrio_slug: 'benipeixcar',
    barrio_nombre_es: 'Benipeixcar',
    barrio_nombre_va: 'Benipeixcar',
    estado: 'completada',
    cronologia: [],
    lat: 38.9716,
    lng: -0.1762,
    created_at: iso('2026-06-20T10:00:00+02:00'),
  },
  {
    slug: 'mesa-jardinet',
    titulo_es: 'Mesa informativa en el Jardinet',
    titulo_va: 'Taula informativa al Jardinet',
    descripcion_es: 'Trabajo de calle para recoger preocupaciones del barrio y presentar líneas de acción.',
    descripcion_va: 'Treball de carrer per recollir preocupacions del barri i presentar línies d’acció.',
    barrio_slug: 'centro',
    barrio_nombre_es: 'Centro',
    barrio_nombre_va: 'Centre',
    estado: 'en_curso',
    cronologia: [],
    lat: 38.968,
    lng: -0.18,
    created_at: iso('2026-06-15T10:00:00+02:00'),
  },
  {
    slug: 'oficina-antiokupacion',
    titulo_es: 'Propuesta oficina antiokupación',
    titulo_va: 'Proposta oficina antiokupació',
    descripcion_es: 'Seguimiento político de la propuesta para crear una oficina especializada.',
    descripcion_va: 'Seguiment polític de la proposta per crear una oficina especialitzada.',
    barrio_slug: 'centro',
    barrio_nombre_es: 'Centro',
    barrio_nombre_va: 'Centre',
    estado: 'propuesta',
    cronologia: [],
    lat: 38.94,
    lng: -0.195,
    created_at: iso('2026-06-10T10:00:00+02:00'),
  },
  {
    slug: 'camaras',
    titulo_es: 'Posición sobre las 38 cámaras de seguridad',
    titulo_va: 'Posició sobre les 38 càmeres de seguretat',
    descripcion_es: 'Seguimiento y defensa pública de una implantación eficaz y proporcionada.',
    descripcion_va: 'Seguiment i defensa pública d’una implantació eficaç i proporcionada.',
    barrio_slug: 'grao',
    barrio_nombre_es: 'Playa-Grao',
    barrio_nombre_va: 'Platja-Grau',
    estado: 'propuesta',
    cronologia: [],
    lat: 38.996,
    lng: -0.155,
    created_at: iso('2026-06-28T10:00:00+02:00'),
  },
  {
    slug: 'mesa-beniopa',
    titulo_es: 'Mesa informativa en Beniopa',
    titulo_va: 'Taula informativa a Beniopa',
    descripcion_es: 'Escucha vecinal y presencia política continuada en el barrio.',
    descripcion_va: 'Escolta veïnal i presència política continuada al barri.',
    barrio_slug: 'beniopa',
    barrio_nombre_es: 'Beniopa',
    barrio_nombre_va: 'Beniopa',
    estado: 'en_curso',
    cronologia: [],
    lat: 38.993,
    lng: -0.162,
    created_at: iso('2026-05-28T10:00:00+02:00'),
  },
];

export const seedEquipo = [
  {
    slug: 'alcazar',
    nombre: 'Alejandro Alcázar',
    cargo_es: 'Presidente',
    cargo_va: 'President',
    bio_es: 'Impulsa la estrategia política y territorial del proyecto.',
    bio_va: 'Impulsa l’estratègia política i territorial del projecte.',
    foto: 'assets/miembro-alcazar.webp',
    orden: 1,
    activo: true,
  },
  {
    slug: 'reig',
    nombre: 'Miguel Reig',
    cargo_es: 'Vicepresidente ejecutivo',
    cargo_va: 'Vicepresident executiu',
    bio_es: 'Coordina organización y seguimiento operativo.',
    bio_va: 'Coordina organització i seguiment operatiu.',
    foto: 'assets/miembro-reig.webp',
    orden: 2,
    activo: true,
  },
  {
    slug: 'mesa',
    nombre: 'Sebastián Mesa',
    cargo_es: 'Tesorero',
    cargo_va: 'Tresorer',
    bio_es: 'Responsable de estructura económica y control interno.',
    bio_va: 'Responsable d’estructura econòmica i control intern.',
    foto: 'assets/miembro-mesa.webp',
    orden: 3,
    activo: true,
  },
];
